<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Inventory;
use App\Models\InventoryMovement;
use App\Models\PackageUnit;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaintStoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::where('role', 'admin')->first() ?? User::first();
        $adminId = $admin?->id;

        // 1. Package Units
        $packageUnitsData = [
            ['name' => 'gallon', 'abbreviation' => 'gal'],
            ['name' => '4-gallon pail', 'abbreviation' => 'pail'],
            ['name' => 'liter', 'abbreviation' => 'L'],
            ['name' => '1/2 liter (pint)', 'abbreviation' => '1/2 L'],
            ['name' => '1/4 liter', 'abbreviation' => '1/4 L'],
            ['name' => '1/8 liter', 'abbreviation' => '1/8 L'],
            ['name' => 'piece', 'abbreviation' => 'pc'],
            ['name' => 'sheet', 'abbreviation' => 'sheet'],
            ['name' => 'roll', 'abbreviation' => 'roll'],
            ['name' => 'bottle', 'abbreviation' => 'btl'],
            ['name' => 'tube', 'abbreviation' => 'tube'],
            ['name' => 'set', 'abbreviation' => 'set'],
            ['name' => 'can', 'abbreviation' => 'can'],
        ];

        $units = [];
        foreach ($packageUnitsData as $u) {
            $unit = PackageUnit::updateOrCreate(
                ['name' => $u['name']],
                ['abbreviation' => $u['abbreviation'], 'active' => true]
            );
            $units[$u['name']] = $unit->id;
        }

        // 2. Categories
        $categoriesData = [
            'Decorative Paints',
            'Enamels & Gloss',
            'Roof & Elastomeric',
            'Primers & Sealers',
            'Automotive Coatings',
            'Thinners & Solvents',
            'Tinting Colors',
            'Putties & Fillers',
            'Painting Tools',
            'Hardware & Tools',
            'Abrasives & Prep',
        ];

        $categories = [];
        foreach ($categoriesData as $c) {
            $isMixing = ($c === 'Tinting Colors');
            $cat = Category::updateOrCreate(
                ['name' => $c],
                ['active' => true, 'is_for_mixing' => $isMixing]
            );
            $categories[$c] = $cat->id;
        }

        // 3. Brands
        $brandsData = [
            'Boysen',
            'Davies',
            'Nippon Paint',
            'Island Paints',
            'Welcoat',
            'Harris',
            'Lotus',
            'Deerfos',
            'Croco',
            'Pioneer',
            'Bostik',
            'Polytuff',
        ];

        $brands = [];
        foreach ($brandsData as $b) {
            $brand = Brand::updateOrCreate(
                ['name' => $b],
                ['active' => true]
            );
            $brands[$b] = $brand->id;
        }

        // 4. Products Master Catalog with Realistic Stock and Peso Prices
        $productsData = [
            // Decorative Paints
            [
                'sku' => 'BOY-PERM-FLAT-4L',
                'name' => 'Boysen Permacoat Flat Latex B-701 White',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 685.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'B-701-4L',
                'description' => '100% acrylic water-based flat paint for exterior and interior concrete and drywall.',
                'stock' => 42.000,
            ],
            [
                'sku' => 'BOY-PERM-FLAT-16L',
                'name' => 'Boysen Permacoat Flat Latex B-701 White (16L Pail)',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => '4-gallon pail',
                'package_size' => 16.000,
                'selling_price' => 2650.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-701-16L',
                'description' => 'Commercial bulk container 16-liter pail of flat latex paint for extensive wall areas.',
                'stock' => 14.000,
            ],
            [
                'sku' => 'BOY-PERM-SEMI-4L',
                'name' => 'Boysen Permacoat Semi-Gloss Latex B-715 White',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 765.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-715-4L',
                'description' => 'Durable water-based semi-gloss finish paint with superior washability and dirt resistance.',
                'stock' => 28.000,
            ],
            [
                'sku' => 'BOY-PERM-SEMI-16L',
                'name' => 'Boysen Permacoat Semi-Gloss Latex B-715 White (16L Pail)',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => '4-gallon pail',
                'package_size' => 16.000,
                'selling_price' => 2980.00,
                'low_stock_threshold' => 3.000,
                'manufacturer_code' => 'B-715-16L',
                'description' => '16-liter pail container of semi-gloss latex paint for high-traffic corridors and rooms.',
                'stock' => 8.000,
            ],
            [
                'sku' => 'BOY-PERM-GLOSS-4L',
                'name' => 'Boysen Permacoat Gloss Latex B-710 White',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 750.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'B-710-4L',
                'description' => 'High-sheen gloss water-based acrylic paint for accent walls, wood, and masonry.',
                'stock' => 3.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-PERM-OFFWHT-4L',
                'name' => 'Boysen Permacoat Flat Latex B-702 Off White',
                'brand' => 'Boysen',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 710.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-702-4L',
                'description' => 'Warm off-white interior finish flat latex paint with anti-fungal properties.',
                'stock' => 15.000,
            ],
            [
                'sku' => 'DAV-MEGA-FLAT-4L',
                'name' => 'Davies Megacryl DV-500 Flat White',
                'brand' => 'Davies',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 670.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'DV-500-4L',
                'description' => '100% premium acrylic flat latex for masonry, concrete, and fiber cement board.',
                'stock' => 22.000,
            ],
            [
                'sku' => 'DAV-MEGA-FLAT-16L',
                'name' => 'Davies Megacryl DV-500 Flat White (16L Pail)',
                'brand' => 'Davies',
                'category' => 'Decorative Paints',
                'unit' => '4-gallon pail',
                'package_size' => 16.000,
                'selling_price' => 2590.00,
                'low_stock_threshold' => 3.000,
                'manufacturer_code' => 'DV-500-16L',
                'description' => 'Bulk 16-liter pail of flat white paint for ceilings and interior walls.',
                'stock' => 7.000,
            ],
            [
                'sku' => 'DAV-MEGA-SEMI-4L',
                'name' => 'Davies Megacryl DV-515 Semi-Gloss White',
                'brand' => 'Davies',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 745.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'DV-515-4L',
                'description' => 'Stain-resistant semi-gloss acrylic finish for kitchens, bathrooms, and exterior walls.',
                'stock' => 16.000,
            ],
            [
                'sku' => 'ISL-PRIMA-FLAT-4L',
                'name' => 'Island Paints Prima Flat Latex White',
                'brand' => 'Island Paints',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 620.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'IP-FLAT-4L',
                'description' => 'Economical premium acrylic flat wall paint for interior architectural applications.',
                'stock' => 12.000,
            ],
            [
                'sku' => 'NIP-WBOND-WHT-4L',
                'name' => 'Nippon Paint Weatherbond Acrylic Exterior White',
                'brand' => 'Nippon Paint',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 890.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'NP-WB-4L',
                'description' => 'Tough exterior weather-defense elastomeric acrylic paint with UV and anti-algae protection.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'WEL-ACRY-WHT-4L',
                'name' => 'Welcoat Acrylic Gloss Latex White',
                'brand' => 'Welcoat',
                'category' => 'Decorative Paints',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 580.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'WC-AGL-4L',
                'description' => 'Cost-effective gloss latex paint for commercial and residential painting projects.',
                'stock' => 18.000,
            ],

            // Enamels & Gloss (Wood & Metal)
            [
                'sku' => 'BOY-QDE-600-4L',
                'name' => 'Boysen Quick Drying Enamel B-600 Gloss White (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 820.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-600-4L',
                'description' => 'Alkyd oil-based high-gloss enamel for interior and exterior wood, steel, and structural metal.',
                'stock' => 25.000,
            ],
            [
                'sku' => 'BOY-QDE-600-1L',
                'name' => 'Boysen Quick Drying Enamel B-600 Gloss White (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 235.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'B-600-1L',
                'description' => '1-liter retail size gloss white quick drying enamel paint for doors, trims, and railings.',
                'stock' => 34.000,
            ],
            [
                'sku' => 'BOY-QDE-630-4L',
                'name' => 'Boysen Quick Drying Enamel B-630 Gloss Black (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 810.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-630-4L',
                'description' => 'Deep gloss black enamel finish for gates, grilles, machinery, and furniture.',
                'stock' => 16.000,
            ],
            [
                'sku' => 'BOY-QDE-630-1L',
                'name' => 'Boysen Quick Drying Enamel B-630 Gloss Black (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 230.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-630-1L',
                'description' => '1-liter can gloss black enamel paint for gates, window grilles, and touch-ups.',
                'stock' => 22.000,
            ],
            [
                'sku' => 'BOY-QDE-650-4L',
                'name' => 'Boysen Quick Drying Enamel B-650 Royal Blue (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 850.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-650-4L',
                'description' => 'Vibrant royal blue gloss alkyd enamel for metal fabrications and wood surfaces.',
                'stock' => 9.000,
            ],
            [
                'sku' => 'BOY-QDE-650-1L',
                'name' => 'Boysen Quick Drying Enamel B-650 Royal Blue (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 245.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-650-1L',
                'description' => '1-liter can royal blue enamel for piping, trim work, and metal furniture.',
                'stock' => 14.000,
            ],
            [
                'sku' => 'BOY-QDE-640-4L',
                'name' => 'Boysen Quick Drying Enamel B-640 Emerald Green (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 850.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-640-4L',
                'description' => 'Classic emerald green gloss enamel coating for architectural metalwork.',
                'stock' => 8.000,
            ],
            [
                'sku' => 'BOY-QDE-671-4L',
                'name' => 'Boysen Quick Drying Enamel B-671 International Red (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 890.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-671-4L',
                'description' => 'Bright safety red gloss enamel for fire prevention pipes, signs, and accents.',
                'stock' => 6.000,
            ],
            [
                'sku' => 'BOY-QDE-671-1L',
                'name' => 'Boysen Quick Drying Enamel B-671 International Red (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 255.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'B-671-1L',
                'description' => '1-liter can international red gloss enamel.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-QDE-680-4L',
                'name' => 'Boysen Quick Drying Enamel B-680 Chocolate Brown (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 830.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'B-680-4L',
                'description' => 'Rich chocolate brown gloss enamel for door frames, fencing, and wooden cabinetry.',
                'stock' => 11.000,
            ],
            [
                'sku' => 'BOY-QDE-621-1L',
                'name' => 'Boysen Quick Drying Enamel B-621 Lemon Yellow (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 250.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-621-1L',
                'description' => '1-liter can lemon yellow gloss enamel for high-visibility fixtures and decor.',
                'stock' => 1.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-QDE-651-1L',
                'name' => 'Boysen Quick Drying Enamel B-651 Sky Blue (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 240.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-651-1L',
                'description' => 'Light sky blue gloss alkyd enamel in convenient 1-liter packaging.',
                'stock' => 10.000,
            ],
            [
                'sku' => 'DAV-QDE-600-4L',
                'name' => 'Davies Quick Drying Enamel DV-600 Gloss White (Gallon)',
                'brand' => 'Davies',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 795.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'DV-600-4L',
                'description' => 'Gloss white alkyd enamel with exceptional leveling and high durability.',
                'stock' => 18.000,
            ],
            [
                'sku' => 'DAV-QDE-670-1L',
                'name' => 'Davies Quick Drying Enamel DV-670 Signal Red (1 Liter)',
                'brand' => 'Davies',
                'category' => 'Enamels & Gloss',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 245.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'DV-670-1L',
                'description' => '1-liter can signal red enamel finish for metal markers and safety borders.',
                'stock' => 8.000,
            ],
            [
                'sku' => 'WEL-FDE-WHT-4L',
                'name' => 'Welcoat Fast Dry Enamel White (Gallon)',
                'brand' => 'Welcoat',
                'category' => 'Enamels & Gloss',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 680.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'WC-FDE-4L',
                'description' => 'Fast-drying economical white enamel paint for metal and wood fabrication.',
                'stock' => 12.000,
            ],

            // Roof & Elastomeric
            [
                'sku' => 'BOY-ROOF-2520-4L',
                'name' => 'Boysen Roofgard B-2520 Spanish Red (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 890.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-2520-4L',
                'description' => '100% acrylic water-based gloss roof paint for galvanized iron and unglazed roof tiles.',
                'stock' => 19.000,
            ],
            [
                'sku' => 'BOY-ROOF-2520-16L',
                'name' => 'Boysen Roofgard B-2520 Spanish Red (16L Pail)',
                'brand' => 'Boysen',
                'category' => 'Roof & Elastomeric',
                'unit' => '4-gallon pail',
                'package_size' => 16.000,
                'selling_price' => 3450.00,
                'low_stock_threshold' => 2.000,
                'manufacturer_code' => 'B-2520-16L',
                'description' => 'Commercial 16-liter pail of spanish red roof paint for residential roofs.',
                'stock' => 1.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-ROOF-2540-4L',
                'name' => 'Boysen Roofgard B-2540 Baguio Green (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 890.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-2540-4L',
                'description' => 'Gloss acrylic roof paint formulated to resist tropical weather and solar degradation.',
                'stock' => 15.000,
            ],
            [
                'sku' => 'BOY-ROOF-2560-4L',
                'name' => 'Boysen Roofgard B-2560 Ocean Blue (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 890.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'B-2560-4L',
                'description' => 'Gloss ocean blue acrylic roof coating with corrosion inhibitor technology.',
                'stock' => 12.000,
            ],
            [
                'sku' => 'DAV-SR-100-4L',
                'name' => 'Davies Sun & Rain SR-100 Opaque White (Gallon)',
                'brand' => 'Davies',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 820.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'SR-100-4L',
                'description' => 'Self-priming elastomeric waterproof wall paint designed to bridge hairline cracks.',
                'stock' => 26.000,
            ],
            [
                'sku' => 'DAV-SR-201-4L',
                'name' => 'Davies Sun & Rain SR-201 Sunshine Yellow (Gallon)',
                'brand' => 'Davies',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 860.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'SR-201-4L',
                'description' => 'Vibrant elastomeric exterior waterproof wall paint.',
                'stock' => 7.000,
            ],
            [
                'sku' => 'DAV-SR-411-4L',
                'name' => 'Davies Sun & Rain SR-411 Bright Green (Gallon)',
                'brand' => 'Davies',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 860.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'SR-411-4L',
                'description' => 'Bright green waterproof elastomeric coating for exterior concrete facades.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'DAV-SR-308-4L',
                'name' => 'Davies Sun & Rain SR-308 Terra Cotta (Gallon)',
                'brand' => 'Davies',
                'category' => 'Roof & Elastomeric',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 840.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'SR-308-4L',
                'description' => 'Earthy terra cotta colored elastomeric exterior waterproofing paint.',
                'stock' => 0.000, // OUT OF STOCK
            ],

            // Primers & Sealers
            [
                'sku' => 'BOY-PRIM-RO-4L',
                'name' => 'Boysen Red Oxide Primer B-310 (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 690.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-310-4L',
                'description' => 'Rust-inhibiting alkyd primer for ferrous metals and structural steel.',
                'stock' => 24.000,
            ],
            [
                'sku' => 'BOY-PRIM-RO-1L',
                'name' => 'Boysen Red Oxide Primer B-310 (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 205.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-310-1L',
                'description' => '1-liter retail can rust-inhibiting red oxide primer for metal components.',
                'stock' => 28.000,
            ],
            [
                'sku' => 'BOY-EPOXY-GRY-4L',
                'name' => 'Boysen Epoxy Primer Gray with Catalyst (Gallon Kit)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 1250.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-EPX-4L',
                'description' => 'Two-component heavy duty epoxy primer kit with curing agent catalyst.',
                'stock' => 10.000,
            ],
            [
                'sku' => 'BOY-FWE-800-4L',
                'name' => 'Boysen Flatwall Enamel B-800 White (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 760.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-800-4L',
                'description' => 'Flat white alkyd undercoat and primer for interior wood work and ceilings.',
                'stock' => 16.000,
            ],
            [
                'sku' => 'BOY-CHALK-7304-4L',
                'name' => 'Boysen Chalk Blocker B-7304 (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 780.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-7304-4L',
                'description' => 'Water-based surface conditioner primer for chalking and weathered concrete walls.',
                'stock' => 6.000,
            ],
            [
                'sku' => 'BOY-PLEX-7760-4L',
                'name' => 'Boysen Plexibond B-7760 Cementitious Waterproofing (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Primers & Sealers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 980.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'B-7760-4L',
                'description' => 'Acrylic polymer bonding agent mixed with Portland cement for positive water barrier.',
                'stock' => 14.000,
            ],

            // Automotive Coatings
            [
                'sku' => 'DAV-KERAM-100-4L',
                'name' => 'Davies Keramifloor KF-100 Light Gray Concrete Floor Paint (Gallon)',
                'brand' => 'Davies',
                'category' => 'Automotive Coatings',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 1050.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'KF-100-4L',
                'description' => 'Two-pack polyamide cured epoxy floor coating for industrial floors and garages.',
                'stock' => 8.000,
            ],
            [
                'sku' => 'DAV-KERAM-400-4L',
                'name' => 'Davies Keramifloor KF-400 Tile Red Concrete Floor Paint (Gallon)',
                'brand' => 'Davies',
                'category' => 'Automotive Coatings',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 1080.00,
                'low_stock_threshold' => 3.000,
                'manufacturer_code' => 'KF-400-4L',
                'description' => 'Abrasion-resistant epoxy floor paint in classic tile red finish.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'DAV-KERAM-300-4L',
                'name' => 'Davies Keramifloor KF-300 Dark Green Concrete Floor Paint (Gallon)',
                'brand' => 'Davies',
                'category' => 'Automotive Coatings',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 1080.00,
                'low_stock_threshold' => 3.000,
                'manufacturer_code' => 'KF-300-4L',
                'description' => 'Heavy-duty industrial floor epoxy enamel in dark green.',
                'stock' => 0.000, // OUT OF STOCK
            ],

            // Thinners & Solvents
            [
                'sku' => 'BOY-THIN-340-4L',
                'name' => 'Boysen Paint Thinner B-0340 Mineral Spirits (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 385.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'B-0340-4L',
                'description' => 'Pure mineral spirits thinner for alkyd enamel paints, varnishes, and brush washing.',
                'stock' => 38.000,
            ],
            [
                'sku' => 'BOY-THIN-340-1L',
                'name' => 'Boysen Paint Thinner B-0340 Mineral Spirits (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 115.00,
                'low_stock_threshold' => 15.000,
                'manufacturer_code' => 'B-0340-1L',
                'description' => '1-liter bottle paint thinner for thinning alkyd paints and cleaning tools.',
                'stock' => 52.000,
            ],
            [
                'sku' => 'BOY-LAQ-350-4L',
                'name' => 'Boysen Lacquer Thinner B-0350 (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 460.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-0350-4L',
                'description' => 'High-grade fast-evaporating solvent for lacquer coatings, primers, and degreasing.',
                'stock' => 30.000,
            ],
            [
                'sku' => 'BOY-LAQ-350-1L',
                'name' => 'Boysen Lacquer Thinner B-0350 (1 Liter)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 130.00,
                'low_stock_threshold' => 12.000,
                'manufacturer_code' => 'B-0350-1L',
                'description' => '1-liter retail bottle lacquer thinner solvent.',
                'stock' => 42.000,
            ],
            [
                'sku' => 'DAV-RED-95-4L',
                'name' => 'Davies Epoxy Reducer DV-95 (Gallon)',
                'brand' => 'Davies',
                'category' => 'Thinners & Solvents',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 580.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'DV-95-4L',
                'description' => 'Specialized reducing solvent formulated for epoxy primers and floor coatings.',
                'stock' => 9.000,
            ],
            [
                'sku' => 'BOY-NEUT-44-1L',
                'name' => 'Boysen B-44 Masonry Neutralizer (1 Liter Bottle)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'bottle',
                'package_size' => 1.000,
                'selling_price' => 110.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-44-1L',
                'description' => 'Mild acid solution used to neutralize alkaline surfaces of newly plastered masonry.',
                'stock' => 15.000,
            ],
            [
                'sku' => 'BOY-REMOV-1415-1L',
                'name' => 'Boysen B-1415 Paint & Varnish Remover (1 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'can',
                'package_size' => 1.000,
                'selling_price' => 220.00,
                'low_stock_threshold' => 4.000,
                'manufacturer_code' => 'B-1415-1L',
                'description' => 'Heavy-duty chemical stripper for stripping old oil paints, varnishes, and enamels.',
                'stock' => 8.000,
            ],
            [
                'sku' => 'LOT-TURP-1L',
                'name' => 'Pure Turpentine Solvent (1 Liter Bottle)',
                'brand' => 'Lotus',
                'category' => 'Thinners & Solvents',
                'unit' => 'bottle',
                'package_size' => 1.000,
                'selling_price' => 95.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'TURP-1L',
                'description' => 'Distilled natural spirits for thinning artist paints, varnishes, and wood polishes.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-BLEACH-SET',
                'name' => 'Boysen Wood Bleach 1 & 2 Complete Set',
                'brand' => 'Boysen',
                'category' => 'Thinners & Solvents',
                'unit' => 'set',
                'package_size' => 1.000,
                'selling_price' => 210.00,
                'low_stock_threshold' => 3.000,
                'manufacturer_code' => 'WB-12-SET',
                'description' => 'Two-part wood bleach solution to lighten natural wood grain and remove stains.',
                'stock' => 0.000, // OUT OF STOCK
            ],

            // Tinting Colors
            [
                'sku' => 'BOY-ACRY-1404',
                'name' => 'Boysen Acry-Color B-1404 Hansa Yellow (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 68.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-1404',
                'description' => 'Water-based concentrated pigment dispersion for tinting acrylic and latex paints.',
                'stock' => 3.000, // LOW STOCK
            ],
            [
                'sku' => 'BOY-ACRY-1405',
                'name' => 'Boysen Acry-Color B-1405 Toluidine Red (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 75.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-1405',
                'description' => 'Concentrated water-dispersible red pigment for custom color shading.',
                'stock' => 16.000,
            ],
            [
                'sku' => 'BOY-ACRY-1406',
                'name' => 'Boysen Acry-Color B-1406 Thalo Blue (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 65.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-1406',
                'description' => 'Concentrated blue tinting color for architectural latex and water-based paints.',
                'stock' => 22.000,
            ],
            [
                'sku' => 'BOY-ACRY-1407',
                'name' => 'Boysen Acry-Color B-1407 Thalo Green (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 68.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-1407',
                'description' => 'Concentrated green colorant for tinting water-based acrylic emulsions.',
                'stock' => 19.000,
            ],
            [
                'sku' => 'BOY-ACRY-1408',
                'name' => 'Boysen Acry-Color B-1408 Lampblack (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 60.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'B-1408',
                'description' => 'Concentrated lampblack colorant for creating grays, charcoal, and dark tints.',
                'stock' => 35.000,
            ],
            [
                'sku' => 'BOY-ACRY-1409',
                'name' => 'Boysen Acry-Color B-1409 Raw Sienna (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 62.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-1409',
                'description' => 'Earth-tone yellow-brown pigment paste for beige, cream, and tan wall shades.',
                'stock' => 17.000,
            ],
            [
                'sku' => 'BOY-OTC-2303',
                'name' => 'Boysen Oil Tinting Color B-2303 Bulletin Red (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 85.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-2303',
                'description' => 'Alkyd-compatible concentrated oil-based red colorant for enamels and varnishes.',
                'stock' => 12.000,
            ],
            [
                'sku' => 'BOY-OTC-2306',
                'name' => 'Boysen Oil Tinting Color B-2306 Prussian Blue (1/4 Liter Can)',
                'brand' => 'Boysen',
                'category' => 'Tinting Colors',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 78.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'B-2306',
                'description' => 'Deep blue oil tinting color for custom shading of alkyd gloss paints.',
                'stock' => 2.000, // LOW STOCK
            ],

            // Putties & Fillers
            [
                'sku' => 'BOY-PUTTY-100-4L',
                'name' => 'Boysen Masonry Putty B-100 (Gallon)',
                'brand' => 'Boysen',
                'category' => 'Putties & Fillers',
                'unit' => 'gallon',
                'package_size' => 4.000,
                'selling_price' => 460.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'B-100-4L',
                'description' => 'Water-based filler putty for patching minor surface imperfections on concrete.',
                'stock' => 26.000,
            ],
            [
                'sku' => 'POLY-BF-1KG',
                'name' => 'Polytuff Polyester Body Filler with Hardener (1kg Can)',
                'brand' => 'Polytuff',
                'category' => 'Putties & Fillers',
                'unit' => 'can',
                'package_size' => 1.000,
                'selling_price' => 245.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'PT-BF-1K',
                'description' => 'Two-part automotive and wood polyester body filler with cream hardener included.',
                'stock' => 20.000,
            ],
            [
                'sku' => 'BOS-VULCA-1L',
                'name' => 'Bostik Super Vulcaseal All-Purpose Sealant (1 Liter Can)',
                'brand' => 'Bostik',
                'category' => 'Putties & Fillers',
                'unit' => 'liter',
                'package_size' => 1.000,
                'selling_price' => 340.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'BS-VLC-1L',
                'description' => 'Elastomeric solvent-based roof and gutter sealant for sealing leak cracks and flashings.',
                'stock' => 3.000, // LOW STOCK
            ],
            [
                'sku' => 'BOS-VULCA-250ML',
                'name' => 'Bostik Super Vulcaseal All-Purpose Sealant (1/4 Liter Can)',
                'brand' => 'Bostik',
                'category' => 'Putties & Fillers',
                'unit' => '1/4 liter',
                'package_size' => 0.250,
                'selling_price' => 110.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'BS-VLC-250',
                'description' => '1/4 liter retail can of Vulcaseal roof and pipe waterproofing sealant.',
                'stock' => 30.000,
            ],
            [
                'sku' => 'PIO-EPOXY-PINT',
                'name' => 'Pioneer All-Purpose Epoxy Components A & B (1 Pint Set)',
                'brand' => 'Pioneer',
                'category' => 'Putties & Fillers',
                'unit' => 'set',
                'package_size' => 1.000,
                'selling_price' => 280.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'PE-AB-PINT',
                'description' => 'High-strength structural epoxy adhesive and bonding agent for wood, concrete, and metals.',
                'stock' => 15.000,
            ],
            [
                'sku' => 'DEX-SILI-300ML',
                'name' => 'Dextone Clear Silicone Sealant Cartridge (300ml Tube)',
                'brand' => 'Pioneer',
                'category' => 'Putties & Fillers',
                'unit' => 'tube',
                'package_size' => 1.000,
                'selling_price' => 165.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'DX-SC-300',
                'description' => '100% acetic silicone sealant for glass, aluminum window frames, and sanitary fixtures.',
                'stock' => 14.000,
            ],

            // Painting Tools
            [
                'sku' => 'HAR-BRUSH-1IN',
                'name' => 'Harris Classic Paint Brush 1" (Bristle)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 35.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'H-CB-1',
                'description' => '1-inch pure bristle paint brush for detail edging, small trims, and touch-ups.',
                'stock' => 38.000,
            ],
            [
                'sku' => 'HAR-BRUSH-2IN',
                'name' => 'Harris Classic Paint Brush 2" (Bristle)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 60.00,
                'low_stock_threshold' => 15.000,
                'manufacturer_code' => 'H-CB-2',
                'description' => '2-inch general-purpose painting brush with ergonomic wooden handle.',
                'stock' => 46.000,
            ],
            [
                'sku' => 'HAR-BRUSH-3IN',
                'name' => 'Harris Classic Paint Brush 3" (Bristle)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 95.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'H-CB-3',
                'description' => '3-inch wide paint brush for medium-sized woodwork, fascia boards, and panels.',
                'stock' => 28.000,
            ],
            [
                'sku' => 'HAR-BRUSH-4IN',
                'name' => 'Harris Classic Paint Brush 4" (Bristle)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 140.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'H-CB-4',
                'description' => '4-inch heavy bristle brush for broad wall painting and masonry waterproofing coating.',
                'stock' => 2.000, // LOW STOCK
            ],
            [
                'sku' => 'HAR-ROL-HD-7IN',
                'name' => 'Harris Heavy Duty Paint Roller with Handle 7"',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 145.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'H-RL-7H',
                'description' => '7-inch heavy duty steel frame paint roller with comfortable grip handle.',
                'stock' => 34.000,
            ],
            [
                'sku' => 'HAR-ROL-REF-7IN',
                'name' => 'Harris Paint Roller Refill 7" (Polyester)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 65.00,
                'low_stock_threshold' => 15.000,
                'manufacturer_code' => 'H-RF-7P',
                'description' => 'High-capacity 7-inch polyester roller sleeve refill for smooth and semi-rough walls.',
                'stock' => 58.000,
            ],
            [
                'sku' => 'HAR-BABY-SET-4IN',
                'name' => 'Harris Mini Baby Roller Set with Handle 4"',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 75.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'H-BR-4S',
                'description' => '4-inch mini roller applicator set for tight corners, cabinets, and door panels.',
                'stock' => 30.000,
            ],
            [
                'sku' => 'HAR-TRAY-9IN',
                'name' => 'Heavy Duty Plastic Paint Tray 9" (Black)',
                'brand' => 'Harris',
                'category' => 'Painting Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 65.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'H-PT-9',
                'description' => 'Heavy duty molded polypropylene paint tray with textured roll-off grid.',
                'stock' => 24.000,
            ],

            // Hardware & Tools
            [
                'sku' => 'LOT-PUTTY-2IN',
                'name' => 'Lotus Stainless Steel Putty Knife (Paleta) 2"',
                'brand' => 'Lotus',
                'category' => 'Hardware & Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 45.00,
                'low_stock_threshold' => 8.000,
                'manufacturer_code' => 'LT-PK-2',
                'description' => '2-inch flexible stainless steel putty blade with comfortable wooden handle.',
                'stock' => 20.000,
            ],
            [
                'sku' => 'LOT-PUTTY-4IN',
                'name' => 'Lotus Stainless Steel Putty Knife (Paleta) 4"',
                'brand' => 'Lotus',
                'category' => 'Hardware & Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 65.00,
                'low_stock_threshold' => 10.000,
                'manufacturer_code' => 'LT-PK-4',
                'description' => '4-inch scraping and patching paleta knife for gypsum, putty, and joint compounds.',
                'stock' => 26.000,
            ],
            [
                'sku' => 'LOT-PUTTY-6IN',
                'name' => 'Lotus Stainless Steel Putty Knife (Paleta) 6"',
                'brand' => 'Lotus',
                'category' => 'Hardware & Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 85.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'LT-PK-6',
                'description' => '6-inch broad joint taping knife for feathering wall surfaces.',
                'stock' => 3.000, // LOW STOCK
            ],
            [
                'sku' => 'LOT-CAULK-GUN-9IN',
                'name' => 'Lotus Heavy Duty Caulking Gun 9"',
                'brand' => 'Lotus',
                'category' => 'Hardware & Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 135.00,
                'low_stock_threshold' => 5.000,
                'manufacturer_code' => 'LT-CG-9',
                'description' => 'Hex-rod skeleton frame applicator gun for standard 300ml silicone and sealant tubes.',
                'stock' => 15.000,
            ],
            [
                'sku' => 'LOT-WIRE-BRUSH',
                'name' => 'Lotus Wire Scratch Brush with Wooden Handle',
                'brand' => 'Lotus',
                'category' => 'Hardware & Tools',
                'unit' => 'piece',
                'package_size' => 1.000,
                'selling_price' => 55.00,
                'low_stock_threshold' => 6.000,
                'manufacturer_code' => 'LT-WB-01',
                'description' => 'Hardened carbon steel wire brush for scraping rust, mill scale, and peeling paint.',
                'stock' => 18.000,
            ],

            // Abrasives & Prep
            [
                'sku' => 'DEER-SAND-100',
                'name' => 'Deerfos Waterproof Silicon Carbide Sandpaper #100 (Coarse)',
                'brand' => 'Deerfos',
                'category' => 'Abrasives & Prep',
                'unit' => 'sheet',
                'package_size' => 1.000,
                'selling_price' => 18.00,
                'low_stock_threshold' => 25.000,
                'manufacturer_code' => 'DF-SP-100',
                'description' => '9x11 inch coarse grit waterproof abrasive paper for heavy wood stripping and rust removal.',
                'stock' => 125.000,
            ],
            [
                'sku' => 'DEER-SAND-180',
                'name' => 'Deerfos Waterproof Silicon Carbide Sandpaper #180 (Medium)',
                'brand' => 'Deerfos',
                'category' => 'Abrasives & Prep',
                'unit' => 'sheet',
                'package_size' => 1.000,
                'selling_price' => 18.00,
                'low_stock_threshold' => 25.000,
                'manufacturer_code' => 'DF-SP-180',
                'description' => 'Medium grit sandpaper for sanding primer coats and smoothing wood grain.',
                'stock' => 98.000,
            ],
            [
                'sku' => 'DEER-SAND-240',
                'name' => 'Deerfos Waterproof Silicon Carbide Sandpaper #240 (Fine)',
                'brand' => 'Deerfos',
                'category' => 'Abrasives & Prep',
                'unit' => 'sheet',
                'package_size' => 1.000,
                'selling_price' => 18.00,
                'low_stock_threshold' => 25.000,
                'manufacturer_code' => 'DF-SP-240',
                'description' => 'Fine grit wet-or-dry sandpaper for smoothing putties before topcoat application.',
                'stock' => 85.000,
            ],
            [
                'sku' => 'DEER-SAND-400',
                'name' => 'Deerfos Waterproof Silicon Carbide Sandpaper #400 (Extra Fine)',
                'brand' => 'Deerfos',
                'category' => 'Abrasives & Prep',
                'unit' => 'sheet',
                'package_size' => 1.000,
                'selling_price' => 20.00,
                'low_stock_threshold' => 20.000,
                'manufacturer_code' => 'DF-SP-400',
                'description' => 'Extra fine grit wet sanding paper for intermediate coat scuffing and automotive prep.',
                'stock' => 52.000,
            ],
            [
                'sku' => 'DEER-SAND-1000',
                'name' => 'Deerfos Waterproof Silicon Carbide Sandpaper #1000 (Ultra Fine Finishing)',
                'brand' => 'Deerfos',
                'category' => 'Abrasives & Prep',
                'unit' => 'sheet',
                'package_size' => 1.000,
                'selling_price' => 24.00,
                'low_stock_threshold' => 15.000,
                'manufacturer_code' => 'DF-SP-1000',
                'description' => 'Ultra fine 1000 grit finishing sandpaper for fine polishing and lacquer finishing.',
                'stock' => 4.000, // LOW STOCK
            ],
            [
                'sku' => 'CRO-TAPE-1IN',
                'name' => 'Croco Premium Masking Tape 1" (24mm x 20m Roll)',
                'brand' => 'Croco',
                'category' => 'Abrasives & Prep',
                'unit' => 'roll',
                'package_size' => 1.000,
                'selling_price' => 32.00,
                'low_stock_threshold' => 20.000,
                'manufacturer_code' => 'CR-MT-24',
                'description' => 'General purpose painter masking tape with clean release and sharp paint lines.',
                'stock' => 75.000,
            ],
            [
                'sku' => 'CRO-TAPE-2IN',
                'name' => 'Croco Premium Masking Tape 2" (48mm x 20m Roll)',
                'brand' => 'Croco',
                'category' => 'Abrasives & Prep',
                'unit' => 'roll',
                'package_size' => 1.000,
                'selling_price' => 62.00,
                'low_stock_threshold' => 15.000,
                'manufacturer_code' => 'CR-MT-48',
                'description' => '2-inch wide masking tape for covering wide baseboards, window glass, and floor edges.',
                'stock' => 40.000,
            ],
        ];

        DB::transaction(function () use ($productsData, $brands, $categories, $units, $adminId): void {
            foreach ($productsData as $data) {
                $brandId = $brands[$data['brand']] ?? null;
                $catId = $categories[$data['category']] ?? null;
                $unitId = $units[$data['unit']] ?? null;

                $product = Product::updateOrCreate(
                    ['sku' => $data['sku']],
                    [
                        'name' => $data['name'],
                        'brand_id' => $brandId,
                        'category_id' => $catId,
                        'package_unit_id' => $unitId,
                        'package_size' => $data['package_size'],
                        'selling_price' => $data['selling_price'],
                        'low_stock_threshold' => $data['low_stock_threshold'],
                        'manufacturer_code' => $data['manufacturer_code'],
                        'description' => $data['description'],
                        'active' => true,
                    ]
                );

                // Set inventory quantity
                $inventory = Inventory::where('product_id', $product->id)->first();
                $existingQty = $inventory ? (float) $inventory->quantity : 0.000;
                $targetQty = (float) $data['stock'];

                if (! $inventory) {
                    Inventory::create([
                        'product_id' => $product->id,
                        'quantity' => $targetQty,
                    ]);

                    if ($targetQty > 0) {
                        InventoryMovement::create([
                            'product_id' => $product->id,
                            'user_id' => $adminId,
                            'type' => 'stock_in',
                            'quantity_change' => $targetQty,
                            'quantity_before' => 0.000,
                            'quantity_after' => $targetQty,
                            'reference_text' => 'Initial Store Inventory Stock',
                        ]);
                    }
                } else {
                    $inventory->update(['quantity' => $targetQty]);
                }
            }
        });
    }
}
