<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Grade A Paint Center - Inventory Stock Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Helvetica, Arial, sans-serif;
            font-size: 9px;
            color: #1f2937;
            margin: 15px;
            line-height: 1.3;
        }
        .header {
            border-bottom: 2px solid #008fb3;
            padding-bottom: 8px;
            margin-bottom: 10px;
        }
        .store-name {
            font-size: 16px;
            font-weight: bold;
            color: #008fb3;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .sub-header {
            font-size: 8.5px;
            color: #6b7280;
            margin: 2px 0 0;
        }
        .report-title {
            font-size: 13px;
            font-weight: bold;
            color: #111827;
            margin: 6px 0 2px;
        }
        .meta-line {
            font-size: 8.5px;
            color: #4b5563;
            margin-bottom: 8px;
        }
        .kpi-container {
            width: 100%;
            margin-bottom: 10px;
            border-collapse: collapse;
        }
        .kpi-box {
            border: 1px solid #e2e8f0;
            background: #f8fafc;
            padding: 5px 8px;
            text-align: center;
        }
        .kpi-label {
            font-size: 7.5px;
            text-transform: uppercase;
            color: #64748b;
            font-weight: bold;
            display: block;
        }
        .kpi-val {
            font-size: 12px;
            font-weight: bold;
            color: #0f172a;
            margin-top: 2px;
            display: block;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 4px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 4px 5px;
            text-align: left;
        }
        table.data-table th {
            background-color: #f1f5f9;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
            color: #334155;
            letter-spacing: 0.3px;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .font-mono {
            font-family: 'DejaVu Sans Mono', 'DejaVu Sans', monospace;
        }
        .status-healthy {
            color: #047857;
            font-weight: bold;
        }
        .status-low {
            color: #b45309;
            font-weight: bold;
        }
        .status-out {
            color: #b91c1c;
            font-weight: bold;
        }
        .footer {
            margin-top: 12px;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
            font-size: 8px;
            color: #94a3b8;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="store-name">Grade A Paint Center</h1>
        <div class="sub-header">Lapu-Lapu St., Agdao, Davao City · POS & Inventory Management System</div>
        <div class="report-title">Inventory Stock Movement & Balance Report</div>
        <div class="meta-line">
            Generated: {{ $generatedAt->format('F d, Y · h:i A') }}
            @if (!empty($generatedBy))
                &nbsp;|&nbsp; <strong>Generated By:</strong> {{ $generatedBy }}
            @endif
            @if (!empty($dateLabel))
                &nbsp;|&nbsp; <strong>Period:</strong> {{ $dateLabel }}
            @endif
            @if (!empty($filterLabel))
                &nbsp;|&nbsp; <strong>Scope:</strong> {{ $filterLabel }}
            @endif
            @if ($stockStatus !== 'all')
                &nbsp;|&nbsp; <strong>Status:</strong> {{ ucfirst($stockStatus) }} Stock
            @endif
        </div>
    </div>

    <!-- Summary KPI Table -->
    <table class="kpi-container">
        <tr>
            <td class="kpi-box">
                <span class="kpi-label">Active SKUs</span>
                <span class="kpi-val">{{ $totalSkus }}</span>
            </td>
            <td class="kpi-box">
                <span class="kpi-label">Low Stock Items</span>
                <span class="kpi-val" style="color: #b45309;">{{ $lowStockCount }}</span>
            </td>
            <td class="kpi-box">
                <span class="kpi-label">Out of Stock</span>
                <span class="kpi-val" style="color: #b91c1c;">{{ $outOfStockCount }}</span>
            </td>
            <td class="kpi-box">
                <span class="kpi-label">Total Stock Valuation</span>
                <span class="kpi-val" style="color: #008fb3;">₱{{ number_format($totalStockValue, 2) }}</span>
            </td>
        </tr>
    </table>

    <!-- Inventory Data Table: SKU first, no unit on stock numbers, starting/in/out/remaining -->
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 10%;">SKU</th>
                <th style="width: 24%;">Product Name</th>
                <th style="width: 6%;">Unit</th>
                <th style="width: 13%;">Brand</th>
                <th style="width: 13%;">Category</th>
                <th style="width: 8%;" class="text-right">Start Bal</th>
                <th style="width: 7%;" class="text-right">Stock In</th>
                <th style="width: 7%;" class="text-right">Stock Out</th>
                <th style="width: 7%;" class="text-right">End Bal</th>
                <th style="width: 5%;" class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($reportItems as $item)
                @php
                    if ($item->remaining_balance <= 0) {
                        $statusClass = 'status-out';
                        $statusText = 'Out';
                    } elseif ($item->remaining_balance <= $item->threshold) {
                        $statusClass = 'status-low';
                        $statusText = 'Low';
                    } else {
                        $statusClass = 'status-healthy';
                        $statusText = 'Healthy';
                    }
                @endphp
                <tr>
                    <td class="font-mono"><strong>{{ $item->sku }}</strong></td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->unit }}</td>
                    <td>{{ $item->brand_name }}</td>
                    <td>{{ $item->category_name }}</td>
                    <td class="text-right font-mono">{{ number_format($item->starting_balance, 2) }}</td>
                    <td class="text-right font-mono" style="color: #047857;">{{ $item->stock_in > 0 ? '+'.number_format($item->stock_in, 2) : '0.00' }}</td>
                    <td class="text-right font-mono" style="color: #b91c1c;">{{ $item->stock_out > 0 ? '-'.number_format($item->stock_out, 2) : '0.00' }}</td>
                    <td class="text-right font-mono" style="font-weight: bold;">{{ number_format($item->remaining_balance, 2) }}</td>
                    <td class="text-center {{ $statusClass }}">{{ $statusText }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="text-center" style="padding: 15px; color: #64748b;">
                        No inventory records match the selected filter criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Grade A Paint Center — Confidential Store Inventory Record — Lapu-Lapu St., Agdao, Davao City
    </div>
</body>
</html>
