<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Grade A Paint Center - Sales Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', Helvetica, Arial, sans-serif;
            font-size: 10px;
            color: #1f2937;
            margin: 15px;
            line-height: 1.3;
        }
        .header {
            border-bottom: 2px solid #008fb3;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }
        .store-name {
            font-size: 18px;
            font-weight: bold;
            color: #008fb3;
            margin: 0;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .sub-header {
            font-size: 9px;
            color: #6b7280;
            margin: 2px 0 0;
        }
        .report-title {
            font-size: 14px;
            font-weight: bold;
            color: #111827;
            margin: 8px 0 2px;
        }
        .meta-line {
            font-size: 9px;
            color: #4b5563;
            margin-bottom: 10px;
        }
        .section-heading {
            font-size: 11px;
            font-weight: bold;
            color: #111827;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin: 14px 0 6px 0;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 3px;
        }
        .kpi-container {
            width: 100%;
            margin-bottom: 12px;
            border-collapse: collapse;
        }
        .kpi-box {
            border: 1px solid #e5e7eb;
            background: #f9fafb;
            padding: 6px 8px;
            text-align: center;
        }
        .kpi-label {
            font-size: 7.5px;
            text-transform: uppercase;
            color: #6b7280;
            font-weight: bold;
            display: block;
        }
        .kpi-val {
            font-size: 12px;
            font-weight: bold;
            color: #111827;
            margin-top: 2px;
            display: block;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 4px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #d1d5db;
            padding: 5px 6px;
            text-align: left;
        }
        table.data-table th {
            background-color: #f3f4f6;
            font-size: 8px;
            font-weight: bold;
            text-transform: uppercase;
            color: #374151;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .font-mono {
            font-family: 'DejaVu Sans Mono', 'DejaVu Sans', monospace;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #e5e7eb;
            padding-top: 6px;
            font-size: 8px;
            color: #9ca3af;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="store-name">Grade A Paint Center</h1>
        <div class="sub-header">Lapu-Lapu St., Agdao, Davao City · POS &amp; Inventory Management System</div>
        <div class="report-title">Sales Revenue &amp; Financial Audit Report</div>
        <div class="meta-line">
            Generated: {{ $generatedAt->format('F d, Y · h:i A') }}
            &nbsp;|&nbsp; <strong>Generated By:</strong> {{ $generatedBy }}
            @if (!empty($filterLabel))
                &nbsp;|&nbsp; <strong>Filters:</strong> {{ $filterLabel }}
            @endif
        </div>
    </div>

    <!-- KPI Summary Row -->
    <table class="kpi-container">
        <tr>
            <td class="kpi-box" style="width: 18%;">
                <span class="kpi-label">Gross Sales</span>
                <span class="kpi-val">₱{{ number_format($grossSubtotal, 2) }}</span>
            </td>
            <td class="kpi-box" style="width: 16%;">
                <span class="kpi-label">Discounts</span>
                <span class="kpi-val" style="color: #b91c1c;">-₱{{ number_format($totalDiscounts, 2) }}</span>
            </td>
            <td class="kpi-box" style="width: 16%;">
                <span class="kpi-label">12% VAT Tax</span>
                <span class="kpi-val" style="color: #6b21a8;">₱{{ number_format($totalTax, 2) }}</span>
            </td>
            <td class="kpi-box" style="width: 20%;">
                <span class="kpi-label">Total Net Revenue</span>
                <span class="kpi-val" style="color: #047857;">₱{{ number_format($totalRevenue, 2) }}</span>
            </td>
            <td class="kpi-box" style="width: 15%;">
                <span class="kpi-label">Completed Orders</span>
                <span class="kpi-val">{{ number_format($totalTransactions) }}</span>
            </td>
            <td class="kpi-box" style="width: 15%;">
                <span class="kpi-label">Avg Order Value</span>
                <span class="kpi-val">₱{{ number_format($avgOrderValue, 2) }}</span>
            </td>
        </tr>
    </table>

    <!-- Daily Breakdown Section -->
    <div class="section-heading">Daily Sales Breakdown</div>
    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 22%;">Date</th>
                <th style="width: 10%;" class="text-center">Orders</th>
                <th style="width: 16%;" class="text-right">Gross Sales</th>
                <th style="width: 14%;" class="text-right">Discounts</th>
                <th style="width: 16%;" class="text-right">12% VAT</th>
                <th style="width: 22%;" class="text-right">Total Revenue</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($dailySummary as $day)
                <tr>
                    <td><strong>{{ \Carbon\Carbon::parse($day->sale_date)->format('M d, Y (D)') }}</strong></td>
                    <td class="text-center">{{ number_format((int) $day->count) }}</td>
                    <td class="text-right">₱{{ number_format((float) $day->gross, 2) }}</td>
                    <td class="text-right" style="color: #b91c1c;">
                        {{ (float) $day->discounts > 0 ? '-₱' . number_format((float) $day->discounts, 2) : '—' }}
                    </td>
                    <td class="text-right" style="color: #6b21a8;">₱{{ number_format((float) $day->tax, 2) }}</td>
                    <td class="text-right font-mono" style="font-weight: bold; color: #047857;">₱{{ number_format((float) $day->revenue, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center" style="padding: 10px; color: #6b7280;">No sales recorded in the selected period.</td>
                </tr>
            @endforelse
        </tbody>
        @if ($dailySummary->isNotEmpty())
            <tfoot>
                <tr style="background-color: #f3f4f6; font-weight: bold;">
                    <td>TOTALS</td>
                    <td class="text-center">{{ number_format($totalTransactions) }}</td>
                    <td class="text-right">₱{{ number_format($grossSubtotal, 2) }}</td>
                    <td class="text-right" style="color: #b91c1c;">-₱{{ number_format($totalDiscounts, 2) }}</td>
                    <td class="text-right" style="color: #6b21a8;">₱{{ number_format($totalTax, 2) }}</td>
                    <td class="text-right font-mono" style="color: #047857;">₱{{ number_format($totalRevenue, 2) }}</td>
                </tr>
            </tfoot>
        @endif
    </table>

    <!-- Top Selling Products Section -->
    @if ($topProducts->isNotEmpty())
        <div class="section-heading">Top Selling Products in Period</div>
        <table class="data-table">
            <thead>
                <tr>
                    <th style="width: 58%;">Product / Item Description</th>
                    <th style="width: 18%;" class="text-right">Units Sold</th>
                    <th style="width: 24%;" class="text-right">Total Sales</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($topProducts as $item)
                    <tr>
                        <td>{{ $item->description }}</td>
                        <td class="text-right font-mono">{{ number_format((float) $item->total_quantity, 2) }}</td>
                        <td class="text-right font-mono" style="font-weight: bold; color: #047857;">₱{{ number_format((float) $item->total_sales, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Grade A Paint Center — Official Sales &amp; Revenue Audit Record — Lapu-Lapu St., Agdao, Davao City
    </div>
</body>
</html>
